spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://192.168.44.131:3306/spring_oauth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: scgcw5053

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8762
  servlet:
    context-path: /uaa
eureka:
  client:
    service-url:
      defauthZone: http://localhost:8761/eureka/
