server:
  port: 8763
spring:
  application:
    name: service-hi
  datasource:
    url: jdbc:mysql://192.168.44.131:3306/spring_oauth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: scgcw5053
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8762/uaa/users/current
      #token-info-uri: http;//loclahost:8762/uaa/oauth/check_token
    client:
      client-id: service-hi
      client-secret: 123456
      access-token-uri: http://localhost:8762/uaa/oauth/token
      grant-type: client_credentials,password
      scope: server

